/**
 * Pay-in `trade_type` and payout `bank_code` values published in the DAYPGL
 * gateway docs (https://doc.daypgl.com/docs/v2/gateway), captured September
 * 2026. Used to offer choices instead of free typing in Payment settings.
 * DAYPGL enables methods per merchant, so a listed code can still be refused
 * and an unlisted one can still be entered by hand.
 */

export type DaypglMethod = readonly [code: string, label: string];

export type DaypglCatalogCountry = {
	name: string;
	currency: string;
	payin: readonly DaypglMethod[];
	payout: readonly DaypglMethod[];
};

export const DAYPGL_CATALOG: Record<string, DaypglCatalogCountry> = {
	BD: {
		name: 'Bangladesh',
		currency: 'BDT',
		payin: [
			['nagad', 'nagad'],
			['bkash', 'bkash'],
			['rocket', 'rocket']
		],
		payout: [
			['2', 'bkash'],
			['1', 'nagad'],
			['3', 'rocket']
		]
	},
	BR: {
		name: 'Brazil',
		currency: 'BRL',
		payin: [['29010', 'PIX']],
		payout: [['bankCode', 'PIX']]
	},
	CO: {
		name: 'Colombia',
		currency: 'COP',
		payin: [['37010', 'Online Banking']],
		payout: [
			['COP001', 'BANCAMIA S.A.'],
			['COP002', 'BANCO AGRARIO'],
			['COP003', 'BANCO AV VILLAS'],
			['COP004', 'BANCO BBVA COLOMBIA S.A.']
		]
	},
	GH: {
		name: 'Ghana',
		currency: 'GHS',
		payin: [['41010', 'Online Banking']],
		payout: [
			['TIGO', 'AirtelTigo Money'],
			['MTN', 'MTN MoMo'],
			['VODAFONE', 'Vodafone Cash']
		]
	},
	HK: {
		name: 'Hong Kong',
		currency: 'HKD',
		payin: [
			['40010', 'Online Banking'],
			['40011', 'FPS']
		],
		payout: [
			['BOCNA', 'BANK OF CHINA'],
			['CITI', 'CITIBANK'],
			['FUBON', 'FUBON BANK'],
			['SCB', 'STANDARD CHARTERED BANK']
		]
	},
	ID: {
		name: 'Indonesia',
		currency: 'IDR',
		payin: [
			['30010', 'Online Banking'],
			['30011', 'QRIS'],
			['30012', 'DANA'],
			['30013', 'OVO'],
			['30014', 'LINKAJA']
		],
		payout: [
			['ACEHIDSS', 'Bank Aceh Syariah'],
			['ARTGIDJA', 'Bank Artha Graha International'],
			['BBLUIDJA', 'Bank BCA Digital (blu)'],
			['BSYAIDJA', 'Bank BCA Syariah'],
			['ABALIDBS', 'Bank BPD Bali'],
			['BCIAIDJA', 'Bank Capital Indonesia'],
			['CENAIDJA', 'Bank Central Asia (BCA)'],
			['BNIAIDJA', 'Bank CIMB Niaga'],
			['BICNIDJA', 'Bank Commonwealth'],
			['CTCBIDJA', 'Bank CTBC Indonesia'],
			['BDINIDJA', 'Bank Danamon Indonesia'],
			['DBSBIDJA', 'Bank DBS Indonesia'],
			['GNESIDJA', 'Bank Ganesha'],
			['HBNIIDJA', 'Bank Hibank Indonesia'],
			['HSBCIDJA', 'Bank HSBC Indonesia'],
			['ICBKIDJA', 'Bank ICBC Indonesia'],
			['IAPTIDJA', 'Bank Ina Perdana'],
			['BIDXIDJA', 'Bank Index Selindo'],
			['JAGBIDJA', 'Bank Jago'],
			['PDJGIDJA', 'Bank Jateng (Jawa Tengah)'],
			['BJTMIDJA', 'Bank Jatim (Jawa Timur)'],
			['HNBNIDJA', 'Bank KEB Hana Indonesia'],
			['ID131', 'Bank Maluku Malut'],
			['BMRIIDJA', 'Bank Mandiri'],
			['MASDIDJS', 'Bank Maspion Indonesia'],
			['MAYAIDJA', 'Bank Mayapada International'],
			['IBBKIDJA', 'Bank Maybank Indonesia'],
			['MEGAIDJA', 'Bank Mega'],
			['BMSIIDJA', 'Bank Mega Syariah'],
			['BMDMIDJA', 'Bank Mestika Dharma'],
			['MUABIDJA', 'Bank Muamalat Indonesia'],
			['NOBUIDJA', 'Bank Nationalnobu (Nobu)'],
			['BNINIDJA', 'Bank Negara Indonesia (BNI)'],
			['ID490', 'Bank Neo Commerce'],
			['ID128', 'Bank NTB Syariah'],
			['NISPIDJA', 'Bank OCBC Indonesia (OCBC NISP)'],
			['BKCHIDJA', 'Bank of China'],
			['PINBIDJA', 'Bank Pan Indonesia (Panin)'],
			['ID132', 'Bank Papua'],
			['PDJBIDJA', 'Bank Pembangunan Daerah Jawa Barat dan Banten (Bank BJB)'],
			['BBBAIDJA', 'Bank Permata'],
			['AWANIDJA', 'Bank QNB Indonesia'],
			['BRINIDJA', 'Bank Rakyat Indonesia (BRI)'],
			['SAHMIDJA', 'Bank Sahabat Sampoerna'],
			['ID472', 'Bank Saqu (Bank Jasa Jakarta)'],
			['SBJKIDJA', 'Bank Sinarmas'],
			['SUNIIDJA', 'Bank SMBC Indonesia (formerly BTPN)'],
			['BSMDIDJA', 'Bank Syariah Indonesia (BSI)'],
			['BBIJIDJA', 'Bank UOB Indonesia'],
			['BVICIDJA', 'Bank Victoria International'],
			['HVBKIDJA', 'Bank Woori Saudara Indonesia 1906'],
			['CITIIDJX', 'Citibank Indonesia'],
			['dana', 'DANA'],
			['IDDANA', 'DANA'],
			['IDGOPAY', 'GoPay'],
			['linkaja', 'Linkaja'],
			['IDLINKAJA', 'LinkAja'],
			['ovo', 'OVO'],
			['IDOVO', 'OVO'],
			['IDSEABANK', 'SeaBank Indonesia'],
			['IDSHOPEEPAY', 'ShopeePay'],
			['SCBLIDJX', 'Standard Chartered Bank Indonesia']
		]
	},
	IN: {
		name: 'India',
		currency: 'INR',
		payin: [
			['091015', 'UPI-NATIVE'],
			['091012', 'UPI-WAKE']
		],
		payout: [
			['INABHYUD', 'Abhyudaya Co-operative Bank'],
			['ADCBINBB', 'Abu Dhabi Commercial Bank India'],
			['APBL', 'Aditya Birla Payments Bank'],
			['INAMCO', 'Ahmedabad Mercantile Co-operative Bank'],
			['ALLA', 'Allahabad Bank'],
			['INAMAZONPAY', 'Amazon Pay'],
			['INAMEX', 'American Express Banking Corporation India'],
			['APGV', 'Andhra Pradesh Grameena Vikas Bank'],
			['INMAHESH', 'Andhra Pradesh Mahesh Co-operative Urban Bank'],
			['APGB', 'Andhra Pragathi Grameena Bank'],
			['APNA', 'APNA SAHAKARI BANK LIMITED'],
			['ARB', 'Arunachal Pradesh Rural Bank'],
			['ARYAVB', 'Aryavart Bank'],
			['AGVB', 'Assam Gramin Vikash Bank'],
			['AUBL', 'AU Small Finance Bank'],
			['ANZBINBB', 'Australia and New Zealand Banking Group India'],
			['UTIB', 'Axis Bank'],
			['BDBL', 'Bandhan Bank'],
			['BGVB', 'Bangiya Gramin Vikash Bank'],
			['DBS', 'Bank DBS Indonesia'],
			['INBANKOFAMERICA', 'Bank of America'],
			['BOFAIN4X', 'Bank of America India'],
			['BBK', 'Bank of Bahrain and Kuwait'],
			['BBKUINBB', 'Bank of Bahrain and Kuwait India'],
			['BARB', 'Bank of Baroda'],
			['BCEYIN5M', 'Bank of Ceylon India'],
			['BKCHINBB', 'Bank of China India'],
			['BKID', 'Bank of India'],
			['MAHB', 'Bank of Maharashtra'],
			['NOSCINBB', 'Bank of Nova Scotia India'],
			['BARCINBB', 'Barclays Bank India'],
			['INBARCLAYSBANKPLC', 'Barclays Bank Plc.'],
			['BGGB', 'Baroda Gujarat Gramin Bank'],
			['BRKGB', 'Baroda Rajasthan Kshetriya Gramin Bank'],
			['INBUPB', 'Baroda UP Bank'],
			['BUPGB', 'Baroda Uttar Pradesh Gramin Bank'],
			['BCCB', 'Bassein Catholic Co-Operative Bank'],
			['BHARATB', 'Bharat Bank'],
			['INBHARATCOOPBANK', 'Bharat Co-op Bank'],
			['INBHARCB', 'Bharat Co-operative Bank'],
			['INBHARATPE', 'BharatPe'],
			['INBHIMUPI', 'BHIM UPI'],
			['BNPAINBB', 'BNP Paribas India'],
			['CNRB', 'Canara Bank'],
			['CLBL', 'Capital Small Finance Bank'],
			['CSBK', 'Catholic Syrian Bank'],
			['CBIN', 'Central Bank of India'],
			['CGGB', 'Chaitanya Godavari Grameena Bank'],
			['CRGB', 'Chhattisgarh Rajya Gramin Bank'],
			['CITI', 'Citi Bank'],
			['CITIINBX', 'Citibank N.A. India'],
			['INCCCB', 'Citizen Credit Co-operative Bank'],
			['CIUB', 'City Union Bank'],
			['CLABL', 'CoastalLocalArea Bank Limited'],
			['RABOINBB', 'Cooperatieve Rabobank India'],
			['CORP', 'Corporation Bank'],
			['INCORPORATIONBANK', 'Corporation Bank'],
			['COSMB', 'Cosmos Bank'],
			['INCOSMOS', 'Cosmos Co-operative Bank'],
			['INCRED', 'CRED'],
			['CRLYINBB', 'Credit Agricole CIB India'],
			['CSBB', 'CSB Bank'],
			['CSYBIN55', 'CSB Bank'],
			['CTCBINDD', 'CTBC Bank India'],
			['DBGB', 'Dakshin Bihar Gramin Bank'],
			['DBSSINBB', 'DBS Bank India'],
			['INDBSBANKLTD', 'DBS Bank LTD'],
			['DCBL', 'DCB Bank'],
			['DCBLINBB', 'DCB Bank'],
			['BKDN', 'Dena Bank'],
			['DSHB', 'Deutsche Bank'],
			['DEUTINBB', 'Deutsche Bank India'],
			['DBOS', 'Development Bank of Singapore'],
			['DHLXM', 'Dhanlaxmi Bank'],
			['INDNLM', 'Dnlm'],
			['DOHBINBB', 'Doha Bank India'],
			['INDNSB', 'Dombivli Nagari Sahakari Bank'],
			['EDB', 'Ellaquai Dehati Bank'],
			['EBILINBM', 'Emirates NBD India'],
			['INEQUITASBANK', 'Equitas Bank'],
			['ESFB', 'Equitas Small Finance Bank'],
			['ESMF', 'ESAF Small Finance Bank'],
			['EXIM', 'Exim Bank'],
			['FDRL', 'Federal Bank'],
			['INFIMONEY', 'Fi Money'],
			['FCSF', 'Fincare Small Finance Bank'],
			['FNPB', 'FINO Payment Bank'],
			['INFINOPB', 'Fino Payments Bank'],
			['FINO', 'FINO PayTech'],
			['NBADINBB', 'First Abu Dhabi Bank India'],
			['INFIRNRD', 'FirstRand Bank India'],
			['INFREECHARGE', 'Freecharge'],
			['INGAMEUPI', 'GAME UPI'],
			['INGPAY', 'Google Pay'],
			['GPPJSB', 'GOPINATH PATIL PARSIK JANATA SAHAKARI BANK LTD'],
			['INGBCB', 'Greater Bombay Co-operative Bank'],
			['HDFC', 'HDFC Bank'],
			['HPGB', 'Himachal Pradesh Gramin Bank'],
			['HSBC', 'HSBC Bank'],
			['HSBCINBB', 'HSBC India'],
			['ICIC', 'ICICI Bank'],
			['ICCB', 'ICICI Corporate Bank'],
			['IBKL', 'IDBI Bank'],
			['INIDFCBANK', 'IDFC Bank'],
			['IDFB', 'IDFC FIRST Bank'],
			['IPOS', 'India Post Payments Bank'],
			['IDIB', 'Indian Bank'],
			['IOBA', 'Indian Overseas Bank'],
			['INDB', 'IndusInd Bank'],
			['ICBKINBB', 'Industrial and Commercial Bank of China India'],
			['IBKOINDD', 'Industrial Bank of Korea India'],
			['IDBI', 'Industrial Development Bank of India'],
			['JKGB', 'J&K Grameen Bank'],
			['JAKA', 'Jammu & Kashmir Bank'],
			['JSFB', 'Jana Small Finance Bank'],
			['INJKSB', 'Janakalyan Sahakari Bank'],
			['INJANSB', 'Janata Sahakari Bank'],
			['JSBP', 'JANATA SAHAKARI BANK LTD PUNE'],
			['JRGB', 'Jharkhand Rajya Gramin Bank'],
			['JIOP', 'Jio Payments Bank'],
			['INJIOMONEY', 'JioMoney'],
			['CHASINBX', 'JPMorgan Chase Bank India'],
			['INJUPITER', 'Jupiter'],
			['INKALUP', 'Kalupur Commercial Co-operative Bank'],
			['INKALYANJANATASAHAKARIBANK', 'Kalyan Janata Sahakari Bank'],
			['KARB', 'Karnataka Bank'],
			['KRGB', 'Karnataka Gramin Bank'],
			['KVGB', 'Karnataka Vikas Grameena Bank'],
			['KVBL', 'Karur Vysya Bank'],
			['KGSG', 'Kashi Gomti Samut Gramin Bank'],
			['INKASHGOMTSAMYGRAMBANK', 'Kashi Gomti Samyut Gramin Bank'],
			['KOEXIN55', 'KEB Hana Bank India'],
			['KLGB', 'Kerala Gramin Bank'],
			['INKOOKMIN', 'Kookmin Bank India'],
			['INKOTAKBANK', 'Kotak Bank'],
			['KKBK', 'Kotak Mahindra Bank'],
			['INKRTH', 'Krung Thai Bank India'],
			['LAVB', 'Lakshmi Vilas Bank'],
			['MBGB', 'Madhya Bihar Gramin Bank'],
			['MPGB', 'Madhya Pradesh Gramin Bank'],
			['MGGB', 'Madhyanchal Gramin Bank'],
			['MAHG', 'Maharashtra Gramin Bank'],
			['MNRB', 'Manipur Rural Bank'],
			['INMASHRQ', 'Mashreqbank India'],
			['MRB', 'Meghalaya Rural Bank'],
			['INMEHUC', 'Mehsana Urban Co-operative Bank'],
			['MZRB', 'Mizoram Rural Bank'],
			['MHCBINBB', 'Mizuho Bank India'],
			['INMOBIKWIK', 'MobiKwik'],
			['BOTKINBB', 'MUFG Bank India'],
			['NGRB', 'Nagaland Rural Bank'],
			['NTBL', 'Nainital Bank'],
			['NABARD', 'National Bank for Agriculture And Rural Development'],
			['NHB', 'National Housing Bank'],
			['INNICB', 'New India Co-operative Bank'],
			['INNIYO', 'Niyo'],
			['INNKGSB', 'NKGSB Co-operative Bank'],
			['NESF', 'North East Small Finance Bank'],
			['NSPB', 'NSDL Payments Bank Limited'],
			['OGB', 'Odisha Gramya Bank'],
			['INOLAMONEY', 'Ola Money'],
			['OBC', 'Oriental Bank of Commerce'],
			['PBG', 'Paschim Banga Gramin Bank'],
			['INPAYTM', 'Paytm'],
			['PPB', 'Paytm Payments Bank'],
			['INPAYZAPP', 'PayZapp'],
			['INPHONEPE', 'PhonePe'],
			['INPRAGKRISGRAMBANK', 'Pragathi Krishna Gramin Bank'],
			['PKGB', 'Pragati Krishna Grameena Bank'],
			['PRTH', 'Prathama UP Gramin Bank'],
			['PBGB', 'Puduvai Bharathiar Grama Bank'],
			['PSIB', 'Punjab & Sind Bank'],
			['PGB', 'Punjab Gramin Bank'],
			['PUNB', 'Punjab National Bank'],
			['PURB', 'Purvanchal Bank'],
			['QNBAINBB', 'Qatar National Bank India'],
			['SBBJ', 'Rajasthan Marudhara Gramin Bank'],
			['INRJNSB', 'Rajkot Nagarik Sahakari Bank'],
			['RATN', 'RBL Bank'],
			['RATNINBB', 'RBL Bank'],
			['RBOI', 'Reserve Bank of India'],
			['RBS', 'Royal Bank of Scotland'],
			['SGB', 'Saptagiri Grameena Bank'],
			['SGGB', 'Sapthagiri Grameena Bank'],
			['SARASWAT', 'Saraswat Bank'],
			['INSARASW', 'Saraswat Co-operative Bank'],
			['SHGB', 'Sarva Haryana Gramin Bank'],
			['SRGB', 'Saurashtra Gramin Bank'],
			['SABRINDD', 'Sberbank India'],
			['STCBINBX', 'SBM Bank India'],
			['SHBKINBB', 'Shinhan Bank India'],
			['INSHVKSFB', 'Shivalik Small Finance Bank'],
			['INSLICSFB', 'Slice Small Finance Bank'],
			['FSFB', 'Small finance bank'],
			['SIDBI', 'Small Industries Development Bank of India'],
			['SOGEINBB', 'Societe Generale India'],
			['INSONALI', 'Sonali Bank India'],
			['SIBL', 'South Indian Bank'],
			['SCBL', 'Standard Chartered Bank'],
			['SCBLINBB', 'Standard Chartered Bank India'],
			['SBH', 'State Bank of Hyderabad'],
			['SBIN', 'State Bank of India'],
			['SLABL', 'Subhadra Local Area Bank ltd'],
			['SSSB', 'Suco Souharda Sahakari Bank'],
			['SMBCINDD', 'Sumitomo Mitsui Banking Corporation India'],
			['SPCB', 'SURAT PEOPLES CO-OP BANK LTD'],
			['SURY', 'Suryoday Small Finance Bank ltd'],
			['INSVCCB', 'SVC Co-operative Bank'],
			['SVCB', 'SVC COOPERATIVE BANK LTD'],
			['SYNB', 'Syndicate Bank'],
			['TNGB', 'Tamil Nadu Grama Bank'],
			['TMBL', 'Tamilnad Mercantile Bank Limited'],
			['SBHY', 'Telangana Grameena Bank'],
			['INTJSB', 'TJSB Sahakari Bank'],
			['TGB', 'Tripura Gramin Bank'],
			['UCBA', 'UCO Bank'],
			['UCBAINBB', 'UCO Bank'],
			['UJVN', 'Ujjivan Small Finance Bank'],
			['UBIN', 'Union Bank of India'],
			['UTBI', 'United Bank India'],
			['INUNITEDBANKOFINDIA', 'United Bank of India'],
			['UOVBINBB', 'United Overseas Bank India'],
			['PMCBINBB', 'Unity Small Finance Bank'],
			['UKGB', 'Utkal Grameen Bank'],
			['INUTKRSFB', 'Utkarsh Small Finance Bank'],
			['UTKS', 'Utkarsh Small Finance Bank in India'],
			['UBGB', 'Uttar Bihar Gramin Bank'],
			['UTKGB', 'Uttarakhand Gramin Bank'],
			['UBKGB', 'Uttarbanga Kshetriya Gramin Bank'],
			['VCGB', 'Vananchal Gramin Bank'],
			['INADITYABIRLAPAYMENTSBANK', 'VeloPayV3-Aditya Birla Payments Bank'],
			['INAIRTELMONEY', 'VeloPayV3-Airtel Money'],
			['INAIRTPB', 'VeloPayV3-Airtel Payments Bank'],
			['INALLAHABADBANK', 'VeloPayV3-Allahabad Bank'],
			['INANDHRABANK', 'VeloPayV3-Andhra Bank'],
			['INAPGVB', 'VeloPayV3-Andhra Pradesh Grameena Vikas Bank'],
			['INAPGB', 'VeloPayV3-Andhra Pragathi Grameena Bank'],
			['INAPNASB', 'VeloPayV3-Apna Sahakari Bank'],
			['INARPRB', 'VeloPayV3-Arunachal Pradesh Rural Bank'],
			['INARYAVARTBANK', 'VeloPayV3-Aryavart Bank'],
			['INAGVB', 'VeloPayV3-Assam Gramin Vikash Bank'],
			['AUBLINBB', 'VeloPayV3-AU Small Finance Bank'],
			['AXISINBB', 'VeloPayV3-Axis Bank'],
			['BNDNINCC', 'VeloPayV3-Bandhan Bank'],
			['INBGVB', 'VeloPayV3-Bangiya Gramin Vikash Bank'],
			['INBANKDBSINDONESIA', 'VeloPayV3-Bank DBS Indonesia'],
			['INBANKOFBAHRAINANDKUWAIT', 'VeloPayV3-Bank Of Bahrain And Kuwait'],
			['BARBINBB', 'VeloPayV3-Bank of Baroda'],
			['BKIDINBB', 'VeloPayV3-Bank of India'],
			['MAHBINBB', 'VeloPayV3-Bank of Maharashtra'],
			['INBGGB', 'VeloPayV3-Baroda Gujarat Gramin Bank'],
			['INBRKGB', 'VeloPayV3-Baroda Rajasthan Kshetriya Gramin Bank'],
			['INBAROUTTAPRADGRAMBANK', 'VeloPayV3-Baroda Uttar Pradesh Gramin Bank'],
			['INBCCB', 'VeloPayV3-Bassein Catholic Co-operative Bank'],
			['CNRBINBB', 'VeloPayV3-Canara Bank'],
			['INCAPTSFB', 'VeloPayV3-Capital Small Finance Bank'],
			['INCATHOLICSYRIANBANK', 'VeloPayV3-Catholic Syrian Bank'],
			['CBININBB', 'VeloPayV3-Central Bank of India'],
			['INCHAIGODAGRAMBANK', 'VeloPayV3-Chaitanya Godavari Grameena Bank'],
			['INCRGB', 'VeloPayV3-Chhattisgarh Rajya Gramin Bank'],
			['CIUBIN5M', 'VeloPayV3-City Union Bank'],
			['INCOASLOCAAREABANKLIMI', 'VeloPayV3-Coastal Local Area Bank Limited'],
			['INCOSMOSBANK', 'VeloPayV3-Cosmos Bank'],
			['INDBGB', 'VeloPayV3-Dakshin Bihar Gramin Bank'],
			['INDENABANK', 'VeloPayV3-Dena Bank'],
			['INDEUTSCHEBANK', 'VeloPayV3-Deutsche Bank'],
			['DLXBINBB', 'VeloPayV3-Dhanlaxmi Bank'],
			['INEDB', 'VeloPayV3-Ellaquai Dehati Bank'],
			['EQTBIN55', 'VeloPayV3-Equitas Small Finance Bank'],
			['ESFAINBB', 'VeloPayV3-ESAF Small Finance Bank'],
			['INEXIMBANK', 'VeloPayV3-Exim Bank'],
			['FDRLINBB', 'VeloPayV3-Federal Bank'],
			['INFINCARESMALLFINANCEBANK', 'VeloPayV3-FINCARE SMALL FINANCE BANK'],
			['INFINOPAYMENTBANK', 'VeloPayV3-Fino Payment Bank'],
			['INGOPIPATIPARSJANASAHABANKLTD', 'VeloPayV3-Gopinath Patil Parsik Janata Sahakari Bank Ltd'],
			['HDFCINBB', 'VeloPayV3-HDFC Bank'],
			['INHPGB', 'VeloPayV3-Himachal Pradesh Gramin Bank'],
			['ICICINBB', 'VeloPayV3-ICICI Bank'],
			['INICICICORPORATEBANK', 'VeloPayV3-ICICI Corporate Bank'],
			['IBKLINBB', 'VeloPayV3-IDBI Bank'],
			['IDFBINBB', 'VeloPayV3-IDFC First Bank'],
			['INIPPBPB', 'VeloPayV3-India Post Payments Bank'],
			['IDIBINBB', 'VeloPayV3-Indian Bank'],
			['IOBAINBB', 'VeloPayV3-Indian Overseas Bank'],
			['INDBINBB', 'VeloPayV3-IndusInd Bank'],
			['INJKGB', 'VeloPayV3-J&K Grameen Bank'],
			['JAKAINBB', 'VeloPayV3-Jammu & Kashmir Bank'],
			['INJANASFB', 'VeloPayV3-Jana Small Finance Bank'],
			['INJANASAHABANKLTDPUNE', 'VeloPayV3-Janata Sahakari Bank Ltd Pune'],
			['INJRGB', 'VeloPayV3-Jharkhand Rajya Gramin Bank'],
			['INJIOPB', 'VeloPayV3-Jio Payments Bank'],
			['KARBINBB', 'VeloPayV3-Karnataka Bank'],
			['INKGB', 'VeloPayV3-Karnataka Gramin Bank'],
			['INKVGB', 'VeloPayV3-Karnataka Vikas Grameena Bank'],
			['KVBLINBB', 'VeloPayV3-Karur Vysya Bank'],
			['INKLGB', 'VeloPayV3-Kerala Gramin Bank'],
			['KKBKINBB', 'VeloPayV3-Kotak Mahindra Bank'],
			['INLAKSHMIVILASBANK', 'VeloPayV3-Lakshmi Vilas Bank'],
			['INMADHYABIHARGRAMINBANK', 'VeloPayV3-Madhya Bihar Gramin Bank'],
			['INMPGB', 'VeloPayV3-Madhya Pradesh Gramin Bank'],
			['INMGB', 'VeloPayV3-Madhyanchal Gramin Bank'],
			['INMHGB', 'VeloPayV3-Maharashtra Gramin Bank'],
			['INMRB', 'VeloPayV3-Manipur Rural Bank'],
			['INMERB', 'VeloPayV3-Meghalaya Rural Bank'],
			['INMZRB', 'VeloPayV3-Mizoram Rural Bank'],
			['INNRB', 'VeloPayV3-Nagaland Rural Bank'],
			['INNAINIT', 'VeloPayV3-Nainital Bank'],
			['INNABARD', 'VeloPayV3-National Bank for Agriculture and Rural Development (NABARD)'],
			['INNATIONALHOUSINGBANK', 'VeloPayV3-National Housing Bank'],
			['INNORTEASTSMALFINABANK', 'VeloPayV3-North East Small Finance Bank'],
			['INNSDLPB', 'VeloPayV3-NSDL Payments Bank'],
			['INODGB', 'VeloPayV3-Odisha Gramya Bank'],
			['INORIENTALBANKOFCOMMERCE', 'VeloPayV3-Oriental Bank Of Commerce'],
			['INPBGB', 'VeloPayV3-Paschim Banga Gramin Bank'],
			['INPAYPAL', 'VeloPayV3-PayPal'],
			['INPAYTPB', 'VeloPayV3-Paytm Payments Bank'],
			['INPUPGB', 'VeloPayV3-Prathama UP Gramin Bank'],
			['INPBGRB', 'VeloPayV3-Puduvai Bharathiar Grama Bank'],
			['PSIBINBB', 'VeloPayV3-Punjab & Sind Bank'],
			['INPGB', 'VeloPayV3-Punjab Gramin Bank'],
			['PUNBINBB', 'VeloPayV3-Punjab National Bank'],
			['INPURVANCHALBANK', 'VeloPayV3-Purvanchal Bank'],
			['INRMGB', 'VeloPayV3-Rajasthan Marudhara Gramin Bank'],
			['INRESERVEBANKOFINDIA', 'VeloPayV3-Reserve Bank of India'],
			['INROYALBANKOFSCOTLAND', 'VeloPayV3-Royal Bank of Scotland'],
			['INSGGB', 'VeloPayV3-Saptagiri Grameena Bank'],
			['INSARASWATBANK', 'VeloPayV3-Saraswat Bank'],
			['INSHGB', 'VeloPayV3-Sarva Haryana Gramin Bank'],
			['INSAGB', 'VeloPayV3-Saurashtra Gramin Bank'],
			['INSMALINDUDEVEBANKOFINDI', 'VeloPayV3-Small Industries Development Bank of India'],
			['SOININ55', 'VeloPayV3-South Indian Bank'],
			['INSTANDARDCHARTEREDBANK', 'VeloPayV3-Standard Chartered Bank'],
			['INSTATEBANKOFHYDERABAD', 'VeloPayV3-State Bank of Hyderabad'],
			['SBININBB', 'VeloPayV3-State Bank of India'],
			['INSUBHADRALOCALAREABANKLTD', 'VeloPayV3-Subhadra Local Area Bank Ltd'],
			['INSURYSFB', 'VeloPayV3-Suryoday Small Finance Bank'],
			['INSYNDICATEBANK', 'VeloPayV3-Syndicate Bank'],
			['INTNGB', 'VeloPayV3-Tamil Nadu Grama Bank'],
			['TMBLINBB', 'VeloPayV3-Tamilnad Mercantile Bank'],
			['INTGGB', 'VeloPayV3-Telangana Grameena Bank'],
			['INTRGB', 'VeloPayV3-Tripura Gramin Bank'],
			['UJSFINBB', 'VeloPayV3-Ujjivan Small Finance Bank'],
			['UBININBB', 'VeloPayV3-Union Bank of India'],
			['INUGB', 'VeloPayV3-Utkal Grameen Bank'],
			['INUBGB', 'VeloPayV3-Uttar Bihar Gramin Bank'],
			['INUKGB', 'VeloPayV3-Uttarakhand Gramin Bank'],
			['INUKGRB', 'VeloPayV3-Uttarbanga Kshetriya Gramin Bank'],
			['INVANANCHALGRAMINBANK', 'VeloPayV3-Vananchal Gramin Bank'],
			['INVKGB', 'VeloPayV3-Vidharbha Konkan Gramin Bank'],
			['INVIJAYABANK', 'VeloPayV3-Vijaya Bank'],
			['VKGB', 'Vidharbha Konkan Gramin Bank'],
			['VIJB', 'Vijaya Bank'],
			['INVTB', 'VTB Bank India'],
			['INWESTPC', 'Westpac Banking Corporation India'],
			['INWHATSAPPPAY', 'WhatsApp Pay'],
			['HVBKIN5M', 'Woori Bank India'],
			['YESB', 'Yes Bank'],
			['YESBINBB', 'Yes Bank']
		]
	},
	KE: {
		name: 'Kenya',
		currency: 'KES',
		payin: [
			['39010', 'Online Banking'],
			['39011', 'EWALLET']
		],
		payout: [
			['KE0038', 'AirtelMoney'],
			['KE0037', 'MPesa']
		]
	},
	KH: {
		name: 'Cambodia',
		currency: 'KHR',
		payin: [
			['44011', 'WingBank'],
			['44010', 'KHQR']
		],
		payout: [
			['ABAAKHPP', 'ABA Bank'],
			['ACLEDA Bank Plc.', 'ACLEDA Bank Plc.'],
			['Aeon Specialized Bank (Cambodia) PLC.', 'Aeon Specialized Bank (Cambodia) PLC.'],
			['Alpha Commercial Bank PLC', 'Alpha Commercial Bank PLC'],
			['AMK Microfinance Plc.', 'AMK Microfinance Plc.'],
			['Amret Plc.', 'Amret Plc.'],
			['ARDB Bank', 'ARDB Bank'],
			['Asia Wei Luy', 'Asia Wei Luy'],
			['ADEOKHPP', 'Asia-Pacific Development Bank Plc (APD Bank)'],
			['IDBCKHPP', 'Bank for Investment and Development of Cambodia (BIDC)'],
			['BKCHKHPP', 'Bank of China (Hong Kong) Limited Phnom Penh Branch'],
			['KHBONGLOY', 'BongLoy'],
			['BKBCKHPP', 'Booyoung Khmer Bank'],
			['BREDKHP2', 'Bred Bank (Cambodia) Plc'],
			['BIDGKHPP', 'Bridge Bank Plc'],
			['CABCKHPP', 'Cambodia Asia Bank Ltd'],
			['CPBPKHP2', 'Cambodia Post Bank Plc (CP Bank)'],
			['CPBLKHPP', 'Cambodian Public Bank (Campu Bank)'],
			['CADIKHPP', 'Canadia Bank Plc'],
			['CSBCKHPP', 'Cathay United Bank (Cambodia) Corporation Ltd'],
			['CLMCKHPP', 'CCU Bank Plc'],
			['CHBCKHPP', 'CHIEF (Cambodia) Commercial Bank Plc'],
			['CHNOKHPP', 'Chip Mong Commercial Bank Plc'],
			['CIBBKHPP', 'CIMB Bank Plc (Cambodia)'],
			['KHCOOLCASH', 'Cool Cash Plc'],
			['KHDARASAKOR', 'Dara Sakor Pay Plc'],
			['DAEBKHPP', 'DGB Specialized Bank Plc'],
			['KHEMONEY', 'eMoney'],
			['FCBKKHPP', 'First Commercial Bank, Phnom Penh Branch'],
			['FTCCKHPP', 'Foreign Trade Bank of Cambodia (FTB)'],
			['HATHKHPP', 'Hattha Bank Plc'],
			['KHHENGFENG', 'Heng Feng (Cambodia) Bank'],
			['HLBBKHPP', 'Hong Leong Bank (Cambodia) Plc'],
			['KHIBANK', 'iBank (Cambodia) Plc'],
			['KHIBKCAM', 'IBK Bank Cambodia Plc'],
			['ICBKKHPP', 'ICBC Limited Phnom Penh Branch'],
			['TCABKHPP', 'J Trust Royal Bank'],
			['CZNBKHPP', 'KB PRASAC Bank Plc'],
			['KHKESS', 'Kess Innovation Plc'],
			['KHLANTON', 'Lanton Pay'],
			['LOLCKHPP', 'LOLC (Cambodia) Plc'],
			['KHLYHOURPAY', 'Ly Hour Pay Pro Plc'],
			['MBBEKHPP', 'Maybank (Cambodia) Plc'],
			['KHMBBANK', 'MB Bank (Cambodia) Plc'],
			['KHMOHANOKOR', 'Mohanokor MFI Plc'],
			['ORENKHPP', 'Oriental Bank Plc'],
			['KHPEAKWEALTH', 'Peak Wealth Bank Plc'],
			['HDSBKHPP', 'Phillip Bank Plc'],
			['PPCBKHPP', 'Phnom Penh Commercial Bank (PPCBank)'],
			['KHPIPAY', 'Pi Pay'],
			['RHBKKHPP', 'RHB Bank (Cambodia) Plc'],
			['KHSACOM', 'Sacombank (Cambodia) Plc'],
			['SBPLKHPP', 'Sathapana Bank Plc'],
			['SBHRKHPP', 'SBI LY HOUR Bank Plc'],
			['SHBKKHPP', 'Shinhan Bank (Cambodia) Plc'],
			['KHTRUEMONEY', 'TrueMoney Cambodia'],
			['KHUPAY', 'U-Pay Digital Plc'],
			['UCBPKHPP', 'Union Commercial Bank Plc (UCB)'],
			['VBLCKHPP', 'Vattanac Bank'],
			['WIGCKHPP', 'Wing Bank (Cambodia) Plc'],
			['HVBKKHPP', 'Woori Bank (Cambodia) Plc']
		]
	},
	MM: {
		name: 'Myanmar',
		currency: 'MMK',
		payin: [
			['26011', 'QR Payment MkbzPay'],
			['26010', 'QR Payment WavePay']
		],
		payout: [
			['MMKBZ_PAY', 'KBZPay (QR)'],
			['WAVE_PAY', 'WavePay (QR)']
		]
	},
	MX: {
		name: 'Mexico',
		currency: 'MXN',
		payin: [
			['28010', 'Online Banking'],
			['28011', 'OXXO'],
			['28012', 'CODI'],
			['28013', 'Bank Transfer']
		],
		payout: [
			['MX138', 'ABC Capital'],
			['MXACTINVER', 'ACTINVER'],
			['MXAFIRME', 'AFIRME'],
			['MXARCUS', 'ARCUS'],
			['MXASPINTEGRAOPC', 'ASP INTEGRA OPC'],
			['MXAUTOFIN', 'AUTOFIN'],
			['MXAZTECA', 'AZTECA'],
			['MXBAJIO', 'BAJIO'],
			['BNMXMXMM', 'Banamex (Banco Nacional de Mexico)'],
			['MXBANAMEX2', 'BANAMEX2'],
			['AFIRMXMT', 'Banca Afirme'],
			['MIFEMXMM', 'Banca Mifel'],
			['ACIOMXMM', 'Banco Actinver'],
			['AUMCMXMM', 'Banco Autofin Mexico'],
			['AZTKMXMM', 'Banco Azteca'],
			['BIBPMXMM', 'Banco Bancrea'],
			['BBSEMXMX', 'Banco Base'],
			['MX124', 'Banco Citi Mexico'],
			['MX130', 'Banco Compartamos'],
			['MX154', 'Banco Covalto (ex Banco Finterra)'],
			['BJIOMXML', 'Banco del Bajio (BanBajio)'],
			['MX166', 'Banco del Bienestar (BaBien)'],
			['MX151', 'Banco Donde'],
			['INBUMXMM', 'Banco Inbursa'],
			['MX150', 'Banco Inmobiliario Mexicano (BIM)'],
			['INXXMXMM', 'Banco Invex'],
			['CHASMXMX', 'Banco J.P. Morgan Mexico'],
			['MONXMXMM', 'Banco Monex'],
			['MIMMMXMX', 'Banco Multiva'],
			['MX148', 'Banco Pagatodo'],
			['MXBANCOS3', 'BANCO S3'],
			['BSMXMXMM', 'Banco S3 Caceis Mexico'],
			['BSABMXMM', 'Banco Sabadell Mexico'],
			['SHBKMXMM', 'Banco Shinhan de Mexico'],
			['MX113', 'Banco Ve por Mas (BX+)'],
			['MX141', 'Banco Volkswagen'],
			['37006', 'BANCOMEXT'],
			['MX006', 'BANCOMEXT'],
			['BNNMMXMM', 'BanCoppel'],
			['MXBANCREA', 'BANCREA'],
			['MX019', 'Banjercito (Banco Nacional del Ejercito)'],
			['MXBANKOFAMERICA', 'BANK OF AMERICA'],
			['BOFAMXMX', 'Bank of America Mexico'],
			['MX147', 'Bankaool'],
			['37009', 'BANOBRAS'],
			['MX009', 'BANOBRAS'],
			['MENOMXMT', 'Banorte (Banco Mercantil del Norte)'],
			['RGIOMXMT', 'Banregio'],
			['SNABMXM1', 'Bansi'],
			['2001', 'BANXICO'],
			['MXBARCLAYS', 'BARCLAYS'],
			['BARCMXMM', 'Barclays Bank Mexico'],
			['MXBBASE', 'BBASE'],
			['BCMRMXMM', 'BBVA Mexico'],
			['MXBMONEX', 'BMONEX'],
			['MXCAJAPOPMEXICA', 'CAJA POP MEXICA'],
			['MXCAJATELEFONIST', 'CAJA TELEFONIST'],
			['MXCBINTERCAM', 'CB INTERCAM'],
			['MXCIBOLSA', 'CI BOLSA'],
			['CIMXMXMM', 'CIBanco'],
			['MXCITIMEXICO', 'CITI MEXICO'],
			['MXCODIVALIDA', 'CoDi Valida'],
			['MXCOMPARTAMOS', 'COMPARTAMOS'],
			['MX140', 'Consubanco'],
			['MXCREDICAPITAL', 'CREDICAPITAL'],
			['MXCREDITSUISSE', 'CREDIT SUISSE'],
			['MXCRISTOBALCOLON', 'CRISTOBAL COLON'],
			['MXCUENCA', 'Cuenca'],
			['MXDONDE', 'DONDE'],
			['MXEVERCORE', 'EVERCORE'],
			['MXFINAMEX', 'FINAMEX'],
			['MXFINCOMUN', 'FINCOMUN'],
			['MXFOMPED', 'FOMPED'],
			['MXFONDEADORA', 'Fondeadora'],
			['MXFONDOFIRA', 'FONDO (FIRA)'],
			['MXGBM', 'GBM'],
			['MXHIPOTECARIAFED', 'HIPOTECARIA FED'],
			['MXHSBC', 'HSBC'],
			['BIMEMXMM', 'HSBC Mexico'],
			['MXICBC', 'ICBC'],
			['ICBKMXMM', 'ICBC Mexico'],
			['MXINBURSA', 'INBURSA'],
			['MXINDEVAL', 'INDEVAL'],
			['MXINMOBILIARIO', 'INMOBILIARIO'],
			['INTEMXMM', 'Intercam Banco'],
			['MXINVERCAP', 'INVERCAP'],
			['MXINVEX', 'INVEX'],
			['MXJPMORGAN', 'JP MORGAN'],
			['MXKLAR', 'Klar'],
			['MXKUSPIT', 'KUSPIT'],
			['MXLIBERTAD', 'LIBERTAD'],
			['MXMASARI', 'MASARI'],
			['MXMERCADOPAGO', 'Mercado Pago'],
			['MXMERCADOPAGOW', 'Mercado Pago W'],
			['MXMIFEL', 'MIFEL'],
			['MXMIZUHOBANK', 'MIZUHO BANK'],
			['MHBMMXMM', 'Mizuho Bank Mexico'],
			['MXMONEXCB', 'MONEXCB'],
			['MXMUFG', 'MUFG'],
			['BOTKMXMX', 'MUFG Bank Mexico'],
			['MXMULTIVABANCO', 'MULTIVA BANCO'],
			['MXMULTIVACBOLSA', 'MULTIVA CBOLSA'],
			['MX135', 'Nacional Financiera (Nafin)'],
			['MX638', 'Nu Mexico'],
			['MXNVIO', 'NVIO Pagos'],
			['MXPAGATODO', 'PAGATODO'],
			['MXPROFUTURO', 'PROFUTURO'],
			['MXREFORMA', 'REFORMA'],
			['MXSABADELL', 'SABADELL'],
			['MXSANTANDER', 'SANTANDER'],
			['BMSXMXMM', 'Santander Mexico'],
			['MXSCOTIABANK', 'SCOTIABANK'],
			['MBCOMXMM', 'Scotiabank Inverlat'],
			['MXSHINHAN', 'SHINHAN'],
			['MX168', 'Sociedad Hipotecaria Federal (SHF)'],
			['MXSPIN', 'Spin by OXXO'],
			['MXSTP', 'STP'],
			['MXTRANSFER', 'TRANSFER'],
			['MXUNAGRA', 'UNAGRA'],
			['MXVALMEX', 'VALMEX'],
			['MXVALUE', 'VALUE'],
			['MXVEPORMAS', 'VE POR MAS'],
			['MXVECTOR', 'VECTOR'],
			['MXVOLKSWAGEN', 'VOLKSWAGEN']
		]
	},
	MY: {
		name: 'Malaysia',
		currency: 'MYR',
		payin: [
			['33010', 'QR Pay'],
			['33011', 'P2P (Bank Transfer)']
		],
		payout: [
			['AFIN', 'AFFIN ISLAMIC BANK'],
			['ALLI', 'ALLIANCE BANK'],
			['SINA', 'BANK SIMPANAN NASIONAL'],
			['CIMB', 'CIMB bank'],
			['CIMB_BIZ', 'CIMB Bank (Corporate Account)'],
			['HOLB', 'HONG LEONG BANK'],
			['MYIS', 'ISLAM BANK'],
			['MAYB', 'Maybank'],
			['MAYB_BIZ', 'Maybank (Corporate Account)'],
			['PBBB', 'Public Bank'],
			['RHBB', 'RHB Bank']
		]
	},
	NG: {
		name: 'Nigeria',
		currency: 'NGN',
		payin: [
			['1601', 'Paga VA'],
			['1602', 'PalmPay bank transfer'],
			['1603', 'PalmPay e-wallet']
		],
		payout: [
			['NGN037', 'AB MICROFINANCE BANK'],
			['NGN038', 'ABBEY MORTGAGE BANK'],
			['NGN039', 'ABOVE ONLY MICROFINANCE BANK'],
			['NGN041', 'ABU Microfinance bank'],
			['NGN042', 'Abucoop Microfinance Bank'],
			['NGN003', 'Access Bank'],
			['NGN043', 'ACCION MFB'],
			['NGN044', 'ADA MICROFINANCE BANK'],
			['NGN046', 'Addosser MFBB'],
			['NGN047', 'ADEYEMI COLLEGE STAFF MICROFINANCE BANK'],
			['NGN049', 'Advans La Fayette'],
			['NGN051', 'AG MORTGAGE BANK PLC'],
			['NGN054', 'AKU MICROFINANCE BANK'],
			['NGN055', 'AL-BARKAH MFB'],
			['NGN056', 'ALEKUN MICROFINANCE BANK'],
			['NGN057', 'ALLWORKERS MFB'],
			['NGN059', 'ALPHAKAPITAL MFB'],
			['NGN061', 'AMAC MICROFINANCE BANK'],
			['NGN062', 'AMJU MFB'],
			['NGN063', 'AMML MFB'],
			['NGN066', 'APEKS Microfinance Bank'],
			['NGN070', 'ASOSavings'],
			['NGN073', 'Astrapolis MFB'],
			['NGN074', 'AUCHI MICROFINANCE BANK'],
			['NGN076', 'AVUENEGBE MICROFINANCE BANK'],
			['NGN081', 'Baines Credit MFB'],
			['NGN086', 'BANKIT MICROFINANCE BANK'],
			['NGN088', 'Baobab Microfinance Bank'],
			['NGN090', 'BC Kash MFB'],
			['NGN092', 'Benysta Microfinance Bank'],
			['NGN097', 'BLOOMS MICROFINANCE BANK'],
			['NGN098', 'Boctrust Microfinance Bank'],
			['NGN101', 'Bold MICROFINANCE BANK'],
			['NGN102', 'Boost MFB'],
			['NGN103', 'Bosak MFB'],
			['NGN104', 'Bowen MFB'],
			['NGN107', 'Brent Mortgage Bank'],
			['NGN116', 'Carbon Microfinance Bank'],
			['NGN119', 'CASHCONNECT MICROFINANCE BANK'],
			['NGN122', 'CEMCS MFB'],
			['NGN124', 'ChamsMobile'],
			['NGN126', 'Chibueze Microfinance Bank'],
			['NGN127', 'Chikum Microfinance Bank'],
			['NGN128', 'Citi Bank'],
			['NGN130', 'CONSUMER MFB'],
			['NGN131', 'Contec Global'],
			['NGN134', 'Corestep Microfinance Bank'],
			['NGN135', 'Coronation'],
			['NGN137', 'Covenant'],
			['NGN138', 'Credit Afrique MFB'],
			['NGN142', 'CRYSTAL MICROFINANCE BANK'],
			['NGN147', 'Daylight Microfinance Bank'],
			['NGN152', 'DOT MICROFINANCE BANK'],
			['NGN153', 'DSC Microfinance Bank'],
			['NGN159', 'e-BARCs MFB'],
			['NGN155', 'EAGLE FLIGHT MFB'],
			['NGN157', 'Eartholeum'],
			['NGN160', 'EBSU MICROFINANCE Bank'],
			['NGN004', 'Ecobank Nigeria'],
			['NGN162', 'Ekondo MFB'],
			['NGN163', 'EMAAR MICROFINANCE BANK'],
			['NGN164', 'EMMAR MICROFINANCE BANK'],
			['NGN165', 'EMPIRE MFB'],
			['NGN167', 'Esan MFB'],
			['NGN168', 'Eso-E Microfinance Bank'],
			['NGN169', 'eTranzact'],
			['NGN170', 'Evib Finance'],
			['NGN171', 'Evib Finance MICROFINANCE BANK'],
			['NGN173', 'EYOWO MICROFINANCE BANK'],
			['NGN176', 'FAST MFB'],
			['NGN177', 'FBN merchant Bank'],
			['NGN178', 'FBN Morgages Limited'],
			['NGN179', 'FCMB'],
			['NGN180', 'FCMB Easy Account'],
			['NGN181', 'FCMB MFB'],
			['NGN182', 'FETS'],
			['NGN184', 'FFS Microfinance Bank'],
			['NGN006', 'Fidelity Bank'],
			['NGN185', 'FidFund MFB'],
			['NGN186', 'FinaTrust Microfinance Bank'],
			['NGN187', 'FINCA MICROFINANCE'],
			['NGN188', 'Finca Microfinance Bank'],
			['NGN189', 'Firmus MICROFINANCE BANK'],
			['NGN190', 'First Ally MFB'],
			['NGN007', 'First Bank of Nigeria'],
			['NGN192', 'First Generation Mortgage Bank'],
			['NGN193', 'First Inland Bank'],
			['NGN195', 'First Multiple MFB'],
			['NGN196', 'First Royal Microfinance Bank'],
			['NGN201', 'FortisMobile'],
			['NGN202', 'Fortress MICROFINANCE BANK'],
			['NGN203', 'FSDH'],
			['NGN204', 'Full range MFB'],
			['NGN205', 'FUTO MFB'],
			['NGN206', 'Gadol Finance'],
			['NGN207', 'Gadol Finance MICROFINANCE BANK'],
			['NGN208', 'GARKI MFB'],
			['NGN210', 'Gashua Microfinance Bank'],
			['NGN211', 'GATEWAY MORTGAGE BANK'],
			['NGN009', 'Globus Bank'],
			['NGN213', 'GOLDMAN MICROFINANCE BANK'],
			['NGN218', 'GOWANS MFB'],
			['NGN222', 'GreenBank MFB'],
			['NGN223', 'GREENVILLE MICROFINANCE BANK'],
			['NGN225', 'Grooming Microfinance bank'],
			['NGN226', 'GT Bank'],
			['NGN227', 'GTMobile'],
			['NGN230', 'Hackman Microfinance Bank'],
			['NGN231', 'Haggai Mortgage Bank'],
			['NGN233', 'HASAL MFB'],
			['NGN235', 'Hedonmark'],
			['NGN241', 'IBILE Microfinance Bank'],
			['NGN246', 'IKIRE MFB'],
			['NGN252', 'IMO MICROFINANCE BANK'],
			['NGN253', 'Imperial Homes Mortgage Bank'],
			['NGN257', 'Infinity MFB'],
			['NGN258', 'Infinity trust Mortgage Bank'],
			['NGN259', 'Intellifin'],
			['NGN260', 'IRL Microfinance Bank'],
			['NGN010', 'Jaiz Bank'],
			['NGN264', 'JubileeLife'],
			['NGN271', 'KCMB MFB'],
			['NGN011', 'Keystone Bank'],
			['NGN277', 'KongaPay'],
			['NGN278', 'KONTAGORA MFB'],
			['NGN012', 'Kuda Bank'],
			['NGN280', 'Lafayette Microfinance Bank'],
			['NGN281', 'Lapo MFB'],
			['NGN282', 'LAVENDER MICROFINANCE BANK'],
			['NGN283', 'LBIC Mortgage Bank'],
			['NGN285', 'Letshego Microfinance Bank'],
			['NGN288', 'Links Microfinance Bank'],
			['NGN292', 'LOVONUS MICROFINANCE BANK'],
			['NGN297', 'Mainstreet MFB'],
			['NGN298', 'Malachy MFB'],
			['NGN301', 'MayFresh Mortgage Bank'],
			['NGN303', 'MEGAPRAISE MICROFINANCE BANK'],
			['NGN306', 'Midland MFB'],
			['NGN310', 'Mkudi'],
			['NGN312', 'MOLUSI MICROFINANCE BANK NIBSS F.I.'],
			['NGN315', 'MoneyBox'],
			['NGN316', 'MONEYFIELD MICROFINA'],
			['NGN318', 'MONEYTRUST MFB'],
			['NGN029', 'Moniepoint Microfinance Bank'],
			['NGN322', 'Mutual Benefits MFB'],
			['NGN323', 'Mutual Trust Microfinance Bank'],
			['NGN325', 'Nargata MFB'],
			['NGN328', 'Ndiorah MFB'],
			['NGN329', 'NEPTUNE MICROFINANCE BANK'],
			['NGN331', 'NEWDAWN MICROFINANCE BANK'],
			['NGN335', 'Nigeria Inter-Bank Settlement System'],
			['NGN338', 'NIRSAL National microfinance bank'],
			['NGN343', 'Nova Bank'],
			['NGN346', 'NPF MicroFinance Bank'],
			['NGN350', 'Nwannegadi MFB'],
			['NGN357', 'OHAFIA MFB'],
			['NGN361', 'Okpoga MFB'],
			['NGN363', 'OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK'],
			['NGN364', 'Old Shoreham MFB'],
			['NGN369', 'OMIYE MFB'],
			['NGN370', 'Omoluabi'],
			['NGN371', 'Omoluabi Mortgage Bank Plc'],
			['NGN001', 'Opay'],
			['NGN373', 'ORAUKWU MICROFINANCE BANK'],
			['NGN375', 'Oscotech MFB'],
			['NGN380', 'Ours MICROFINANCE BANK'],
			['NGN382', 'Page MFBank'],
			['NGN002', 'PalmPay'],
			['NGN384', 'Parkway-ReadyCash'],
			['NGN014', 'Parralex Microfinance Bank'],
			['NGN385', 'PATHFINDER MFB'],
			['NGN386', 'PATHFINDER MICROFINANCE BANK'],
			['NGN387', 'Patrickgold MFB'],
			['NGN389', 'Peace Microfinance Bank'],
			['NGN390', 'Pecan Trust Microfinance Bank'],
			['NGN391', 'Pennywise Microfinance bank'],
			['NGN393', 'Personal Trust Microfinance Bank'],
			['NGN394', 'Petra Microfinance Bank'],
			['NGN396', 'PLATINUM MORTGAGE BANK'],
			['NGN398', 'PocketApp'],
			['NGN015', 'Polaris Bank'],
			['NGN402', 'Preeminent Microfinance Bank'],
			['NGN404', 'PRESTIGE MICROFINANCE BANK'],
			['NGN016', 'Providus Bank'],
			['NGN411', 'QUICKFUND MICROFINANCE BANK'],
			['NGN412', 'Rahama MFB'],
			['NGN413', 'Rand Merchant Bank'],
			['NGN415', 'Refuge Mortgage Bank'],
			['NGN416', 'REGENT MFB'],
			['NGN417', 'Reliance MFB'],
			['NGN418', 'Renmoney Microfinance Bank'],
			['NGN422', 'RICHWAY MFB'],
			['NGN423', 'RIGO Microfinance Bank'],
			['NGN425', 'Royal Exchange Microfinance Bank'],
			['NGN428', 'SABI MICROFINANCE BANK'],
			['NGN430', 'SafeHaven Microfinance Bank'],
			['NGN431', 'SafeTrust'],
			['NGN432', 'Safetrust Mortgage Bank Limited'],
			['NGN433', 'Sagamu Microfinance Bank'],
			['NGN435', 'Seed Capital Microfinance Bank'],
			['NGN436', 'SEEDVEST MICROFINANCE BANK'],
			['NGN441', 'SINCERE MICROFINANCE BANK'],
			['NGN017', 'StanbicIBTC Bank'],
			['NGN451', 'Standard MFB'],
			['NGN018', 'StandardChartered'],
			['NGN452', 'Stanford MFB'],
			['NGN453', 'STELLAS MICROFINANCE BANK'],
			['NGN019', 'Sterling Bank'],
			['NGN455', 'Sunbeam Microfinance Bank'],
			['NGN020', 'Suntrust Bank'],
			['NGN459', 'TagPay'],
			['NGN022', 'TAJ Bank'],
			['NGN461', 'TCF'],
			['NGN462', 'TeasyMobile'],
			['NGN466', 'TITAN TRUST BANK'],
			['NGN471', 'Trident Microfinance Bank'],
			['NGN473', 'Trustbond'],
			['NGN474', 'TRUSTFUND MICROFINANCE BANK NIBSS F.I.'],
			['NGN486', 'UNIBEN MICROFINANCE BANK'],
			['NGN487', 'Unical MFB'],
			['NGN023', 'Union Bank'],
			['NGN024', 'United Bank For Africa'],
			['NGN025', 'Unity Bank'],
			['NGN489', 'UniUyo Microfinance Bank'],
			['NGN490', 'UNN MFB'],
			['NGN493', 'Uzondu MF Bank'],
			['NGN495', 'Verite Microfinance Bank'],
			['NGN026', 'VFD Microfinance Bank'],
			['NGN497', 'Virtue MFB'],
			['NGN498', 'Visa Microfinance Bank NIBSS F.I.'],
			['NGN499', 'Vista MICROFINANCE BANK'],
			['NGN500', 'VTNetworks'],
			['NGN027', 'Wema Bank'],
			['NGN506', 'WETLAND MFB'],
			['NGN508', 'WinView Bank'],
			['NGN511', 'XSLNCE Microfinance Bank'],
			['NGN512', 'Yes MFB'],
			['NGN028', 'Zenith Bank']
		]
	},
	NP: {
		name: 'Nepal',
		currency: 'NPR',
		payin: [['45010', 'Fonepay QR']],
		payout: [
			['ADBLNPKA', 'Agricultural Development Bank Limited'],
			['CTZNNPKA', 'Citizens Bank International Limited'],
			['NPCORPORATEDB', 'Corporate Development Bank Limited'],
			['EVBLNPKA', 'Everest Bank Limited'],
			['NPEXCELDB', 'Excel Development Bank Limited'],
			['NPGARIMADB', 'Garima Bikas Bank Limited'],
			['GLBBNPKA', 'Global IME Bank Limited'],
			['NPGREENDB', 'Green Development Bank Limited'],
			['HIMANPKA', 'Himalayan Bank Limited'],
			['NPJYOTIDB', 'Jyoti Bikas Bank Limited'],
			['NPKAMANASEWADB', 'Kamana Sewa Bikas Bank Limited'],
			['NPKARNALIDB', 'Karnali Development Bank Limited'],
			['KMBLNPKA', 'Kumari Bank Limited'],
			['LXBLNPKA', 'Laxmi Sunrise Bank Limited'],
			['NPLUMBINIDB', 'Lumbini Bikas Bank Limited'],
			['MBLNNPKA', 'Machhapuchhre Bank Limited'],
			['NPMAHALAXMIDB', 'Mahalaxmi Bikas Bank Limited'],
			['NPMITERIDB', 'Miteri Development Bank Limited'],
			['NPMUKTINATHDB', 'Muktinath Bikas Bank Limited'],
			['NARBNPKA', 'Nabil Bank Limited'],
			['NPNARAYANIDB', 'Narayani Development Bank Limited'],
			['NEBLNPKA', 'Nepal Bank Limited'],
			['NIBLNPKT', 'Nepal Investment Mega Bank Limited'],
			['NSBINPKA', 'Nepal SBI Bank Limited'],
			['NICENPKA', 'NIC Asia Bank Limited'],
			['NMBBNPKA', 'NMB Bank Limited'],
			['PRVUNPKA', 'Prabhu Bank Limited'],
			['PCBLNPKA', 'Prime Commercial Bank Limited'],
			['RBBANPKA', 'Rastriya Banijya Bank Limited'],
			['NPSALAPADB', 'Salapa Bikash Bank Limited'],
			['NPSANGRILADB', 'Sangrila Development Bank Limited'],
			['SNMANPKA', 'Sanima Bank Limited'],
			['NPSAPTAKOSHIDB', 'Saptakoshi Development Bank Limited'],
			['NPSHINERESUNGADB', 'Shine Resunga Development Bank Limited'],
			['SIDDNPKA', 'Siddhartha Bank Limited'],
			['NPSINDHUDB', 'Sindhu Bikas Bank Limited'],
			['SCBLNPKA', 'Standard Chartered Bank Nepal Limited']
		]
	},
	PE: {
		name: 'Peru',
		currency: 'PEN',
		payin: [
			['38010', 'Online Banking'],
			['38011', 'QR Payment']
		],
		payout: []
	},
	PH: {
		name: 'Philippines',
		currency: 'PHP',
		payin: [
			['GCashWAP', 'Gcash'],
			['Maya', 'Maya'],
			['Gotyme', 'Gotyme']
		],
		payout: [
			['GCash', 'Gcash'],
			['GW_GOT', 'Gotyme'],
			['maya', 'Maya']
		]
	},
	PK: {
		name: 'Pakistan',
		currency: 'PKR',
		payin: [
			['27010', 'Jazzcash'],
			['27011', 'Easypaisa']
		],
		payout: [
			['016', 'Al Baraka Bank Limited'],
			['AIINPKKA', 'Al Baraka Bank Limited'],
			['PKALBARAKAISLAMICBANK', 'Al Baraka Islamic Bank'],
			['014', 'Allied Bank Limited'],
			['ABPAPKKA', 'Allied Bank Limited'],
			['017', 'Askari Bank Limited'],
			['ASCMPKKA', 'Askari Bank Limited'],
			['051', 'Bank Al Falah Limited'],
			['ALFHPKKA', 'Bank Al Falah Limited'],
			['023', 'Bank Al Habib Limited'],
			['BAHLPKKA', 'Bank Al Habib Limited'],
			['021', 'Bank Islami Pakistan Limited'],
			['PKBANKISLAPAKILIMI', 'Bank Islami Pakistan Limited'],
			['SUMBPKKA', 'Bank Makramah Limited'],
			['061', 'Bank of Khyber'],
			['KHYBPKKA', 'Bank of Khyber'],
			['083', 'Bank of Punjab'],
			['BPUNPKKA', 'Bank of Punjab'],
			['BKIPPKKA', 'BankIslami Pakistan Limited'],
			['046', 'Citi Bank'],
			['CITIPKKX', 'Citi Bank'],
			['PKCITIBANKNA', 'Citi Bank'],
			['013', 'Dubai Islamic Bank Pakistan Li'],
			['DUIBPKKA', 'Dubai Islamic Bank Pakistan Limited'],
			['EASYPAISA', 'Easypaisa'],
			['096', 'Easypaisa-TelenorBank'],
			['PKEASYPAISA', 'Easypaisa-TelenorBank'],
			['PKEPB', 'Easypaisa-TelenorBank'],
			['060', 'Faysal Bank Limited'],
			['FAYSPKKA', 'Faysal Bank Limited'],
			['091', 'FINCA Microfinance'],
			['PKFINCA', 'FINCA Microfinance'],
			['PKFINCMICRBANKFINC', 'FINCA Microfinance Bank FINCA'],
			['054', 'Habib Bank Limited'],
			['HABBPKKA', 'Habib Bank Limited'],
			['064', 'Habib Metropolitan Bank'],
			['MPBLPKKA', 'Habib Metropolitan Bank'],
			['PKHBLMFB', 'HBL Microfinance Bank Limited'],
			['097', 'JazzCash'],
			['PKJAZZCASH', 'JazzCash'],
			['018', 'JS Bank'],
			['JSBLPKKA', 'JS Bank Limited'],
			['062', 'MCB Bank Limited'],
			['MUCBPKKA', 'MCB Bank Limited'],
			['063', 'MCB Islamic'],
			['MCIBPKKI', 'MCB Islamic'],
			['089', 'Meezan Bank Limited'],
			['MEZNPKKA', 'Meezan Bank Limited'],
			['PKMMBL', 'Mobilink Microfinance Bank Limited'],
			['070', 'National Bank Limited'],
			['NBPAPKKA', 'National Bank of Pakistan'],
			['090', 'NRSP Bank'],
			['PKNRSP', 'NRSP Microfinance Bank Limited'],
			['028', 'Samba Bank Limited'],
			['SAMBPKKA', 'Samba Bank Limited'],
			['PKSILKBANKLIMITED', 'Silk Bank Limited'],
			['066', 'Silkbank Limited'],
			['085', 'Soneri Bank Limited'],
			['SONEPKKA', 'Soneri Bank Limited'],
			['038', 'Standard Chartered Bank'],
			['SCBLPKKX', 'Standard Chartered Bank'],
			['081', 'Summit Bank'],
			['PKSUMMITBANKLIMITED', 'Summit Bank'],
			['PKTELENORMICROFINANCEBANK', 'Telenor Microfinance Bank'],
			['094', 'The First Microfinance Bank'],
			['PKUMFB', 'U Microfinance Bank Limited'],
			['095', 'UBank/UPaisa'],
			['PKUPAISA', 'UBank/UPaisa'],
			['086', 'United Bank Limited'],
			['UNILPKKA', 'United Bank Limited']
		]
	},
	RU: {
		name: 'Russia',
		currency: 'RUB',
		payin: [
			['42010', 'Online Banking'],
			['42011', 'SBP']
		],
		payout: [
			['ABSL', 'ABSOLYUT_BANK'],
			['AGZA', 'BANK_AGROROS'],
			['AKCB', 'BANK_AKCEPT'],
			['AGCO', 'KB_AGROPROMKREDIT']
		]
	},
	SG: {
		name: 'Singapore',
		currency: 'SGD',
		payin: [['36010', 'Online Banking']],
		payout: [
			['DBS', 'DBS Bank'],
			['PNSG', 'Paynow Singapore'],
			['UOB', 'United Overseas Bank']
		]
	},
	TH: {
		name: 'Thailand',
		currency: 'THB',
		payin: [['bank', 'QR Payment (QR BANK)']],
		payout: [
			['ABI', 'Agrigol Bank Indonesia'],
			['AIG', 'AIG Retail Bank Public Company Limited'],
			['ANZ', 'ANZ BANK (THAI) PUBLIC CO., LTD'],
			['BKKB', 'Bangkok Bank'],
			['BAAC', 'Bank for Agriculture and Agricultural Cooperatives'],
			['BOFATH', 'BANK OF AMERICA, N.A. BANGKOK BIC'],
			['BOC', 'BANK OF CHINA (THAI) PUBLIC CO., LTD'],
			['BNPP', 'BNP PARIBAS'],
			['CIMB', 'CIMB THAI BANK PUBLIC CO., LTD.'],
			['CITI', 'CITIBANK, N.A'],
			['DEUT', 'DEUTSCHE BANK AG.'],
			['EXIMTHB', 'EXPORT-IMPORT BANK OF THAILAND'],
			['GHB', 'GOVERNMENT HOUSING BANK'],
			['GSB', 'GOVERNMENT SAVINGS BANK'],
			['IOB', 'Indian Overseas Bank'],
			['ICBC', 'INDUSTRIAL AND COMMERCIAL BANK OF CHINA (THAI) PUBLIC CO., LTD'],
			['ISBT', 'ISLAMIC BANK OF THAILAND'],
			['KBANK', 'KASIKORNBANK PUBLIC CO., LTD.'],
			['KKP', 'KIATNAKIN BANK PUBLIC CO., LTD.'],
			['KTB', 'Krung Thai Bank'],
			['KSAB', 'Krungsri Bank(Bank of Ayudhya)'],
			['LHB', 'LAND AND HOUSES BANK PUBLIC CO., LTD.'],
			['MIZUHO', 'MIZUHO BANK, LTD. BANGKOK BRANCH'],
			['OVCBCTHB', 'Oversea Chinese Banking Corp. Ltd. 040 OCBCTHBK'],
			['DCBBTH', 'RHB BANK BERHAD'],
			['SCB', 'Siam Commercial Bank'],
			['SMEBTHBK', 'SMALL AND MEDIUM ENTERPRISE DEVELOPMENT BANK OF THAILAND'],
			['SCBT', 'Standard Chartered Bank (Thai)'],
			['SMBC', 'SUMITOMO MITSUI BANKING CORPORATION'],
			['TCB', 'THAI CREDIT BANK PUBLIC COMPANY'],
			['HSBC', 'THE HONGKONG AND SHANGHAI BANKING CORPORATION LIMITED'],
			['RBS', 'THE ROYAL BANK OF SCOTLAND PLC'],
			['TCR', 'THE THAI CREDIT RETAIL BANK PUBLIC CO., LTD.'],
			['TISC', 'TISCO Bank'],
			['TTB', 'TMBTHANACHART BANK PUBLIC CO., LTD'],
			['UOBT', 'United Overseas Bank (Thai)']
		]
	},
	TZ: {
		name: 'Tanzania',
		currency: 'TZS',
		payin: [['43010', 'EWALLET']],
		payout: [
			['Halo', 'HaloPesa'],
			['voda', 'vodacom']
		]
	},
	US: {
		name: 'United States',
		currency: 'USD',
		payin: [
			['1301', 'CashApp'],
			['1302', 'ApplePay'],
			['1303', 'GooglePay'],
			['1304', 'btcpay'],
			['1305', 'Paypal']
		],
		payout: [
			['ACH', 'ACH'],
			['CASHAPP', 'Cash App'],
			['Chime', 'Chime'],
			['CARD', 'DebitCard'],
			['PayPal', 'PayPal']
		]
	},
	VN: {
		name: 'Vietnam',
		currency: 'VND',
		payin: [['31010', 'QR Payment']],
		payout: [
			['ABCVN', 'Agricultural Bank of China Limited – Vietnam Branch'],
			['ABBANK', 'An Binh Commercial Joint Stock Bank'],
			['ABBKVNVX', 'An Binh Commercial Joint Stock Bank (ABBANK)'],
			['ANZBVNVX', 'ANZ Bank (Vietnam) Limited'],
			['ASCBVNVX', 'Asia Commercial Bank (ACB)'],
			['ACB', 'Asia Commercial Joint Stock Bank'],
			['NASCVNVX', 'Bac A Commercial Joint Stock Bank (Bac A Bank)'],
			['BacABank', 'BacABank'],
			['BKKBVNVX', 'Bangkok Bank PCL - Ho Chi Minh City Branch'],
			['BIDVVNVX', 'Bank for Investment and Development of Vietnam (BIDV)'],
			['VNBANKFORINVEDEVEOFVIET', 'Bank for Investment-Development of Vietnam'],
			['BKCHVNVX', 'Bank of China (Hong Kong) Limited - Ho Chi Minh City Branch'],
			['BVBVVNVX', 'Bao Viet Joint Stock Commercial Bank (BaoViet Bank)'],
			['BaoVietBank', 'BaoVietBank'],
			['VNBAOVIETBANK', 'BaoVietBank'],
			['BIDV', 'BIDV'],
			['BizMBBank', 'BizMBBank'],
			['BNPAVNVX', 'BNP Paribas - Ho Chi Minh City Branch'],
			['cake by vpbank', 'cake by vpbank'],
			['VNCAKEBANK', 'Cake Digital Bank by VPBank'],
			['VNCATHAY', 'Cathay United Bank - Vietnam Branch'],
			['CBBank', 'CBBank'],
			['PCBCVNVX', 'China Construction Bank - Ho Chi Minh City Branch'],
			['CIBBVNVN', 'CIMB Bank (Vietnam) Limited'],
			['CIMB', 'CIMB Bank Vietnam Limited'],
			['Citibank N.A', 'Citibank N.A'],
			['CITIVNVX', 'Citibank N.A. Vietnam'],
			['Citibank', 'Citibank, N.A. – Vietnam Branch'],
			['VNCOOPBANK', 'Co-operative Bank of Vietnam (Co-opBank)'],
			['COOPBANK', 'COOPBANK'],
			['DBSBank', 'DBS Bank Ltd. – Vietnam Branch'],
			['DEUTVNVX', 'Deutsche Bank AG - Ho Chi Minh City Branch'],
			['EACBVNVX', 'Dong A Commercial Joint Stock Bank (DongA Bank)'],
			['Eximbank', 'Eximbank'],
			['LVBKVNVX', 'Fortune Vietnam Joint Stock Commercial Bank (LPBank)'],
			['GDB', 'Global Development Bank'],
			['GPBank', 'Global Petro Commercial Joint Stock Bank'],
			['GBNKVNVX', 'Global Petro Commercial Joint Stock Bank (GPBank)'],
			['VNHDBHOCHIMINCITYDEVEJOINSTOCCOMMBANK', 'HDB-Ho Ch iMinh City Development Joint Stock Commercial Bank'],
			['HDBank', 'HDBank'],
			['HDBCVNVX', 'Ho Chi Minh City Development Joint Stock Commercial Bank (HDBank)'],
			['HongLeong', 'Hong Leong Bank Vietnam Limited'],
			['HLBBVNVX', 'Hong Leong Bank Vietnam Limited'],
			['HSBC', 'HSBC Bank (Vietnam) Ltd'],
			['HSBCVNVX', 'HSBC Bank (Vietnam) Ltd.'],
			['IBKHN', 'IBKHN'],
			['IABBVNVX', 'Indovina Bank Ltd.'],
			['IndovinaBank', 'IndovinaBank'],
			['ICBKVNVX', 'Industrial and Commercial Bank of China (ICBC) - Hanoi Branch'],
			['IBK Bank', 'Industrial Bank of Korea – Vietnam Branch'],
			['VNIBK', 'Industrial Bank of Korea (IBK) - Vietnam Branch'],
			['Vietcomban', 'Joint Stock Commercial Bank for Foreign Trade of Vietnam'],
			['BFTVVNVX', 'Joint Stock Commercial Bank for Foreign Trade of Vietnam (Vietcombank)'],
			['KASIVNVX', 'Kasikornbank PCL (KBank) - Ho Chi Minh City Branch'],
			['kbank', 'kbank'],
			['KBHCM', 'KBHCM'],
			['KEBHANAHN', 'KEBHANAHN'],
			['KLBKVNVX', 'Kien Long Commercial Joint Stock Bank (Kienlongbank)'],
			['KienLongBank', 'KienLongBank'],
			['VNKOOKMIN', 'Kookmin Bank - Vietnam Branch'],
			['KookminHN', 'KookminHN'],
			['LPBank', 'Lien Viet Post Joint Stock Commercial Bank'],
			['LIENVIETPOSTBANK', 'LIENVIETPOSTBANK'],
			['VNLIOBANK', 'Liobank by OCB'],
			['MAFC', 'MAFC'],
			['VNMAYBANK', 'Malayan Banking Berhad (Maybank) - Vietnam Branch'],
			['Mandiri Bank', 'Mandiri Bank'],
			['VNMARITIMEBANK', 'Maritime Bank'],
			['MBV Bank', 'MBV Bank'],
			['Mega', 'Mega'],
			['MBBank', 'Military Commercial Joint Stock Bank'],
			['MSCBVNVX', 'Military Commercial Joint Stock Bank (MB Bank)'],
			['MHCBVNVX', 'Mizuho Bank, Ltd. - Hanoi Branch'],
			['BOTKVNVX', 'MUFG Bank, Ltd. - Ho Chi Minh City Branch'],
			['NAMAVNVX', 'Nam A Commercial Joint Stock Bank (Nam A Bank)'],
			['NamABank', 'NamABank'],
			['NVBAVNVX', 'National Citizen Commercial Joint Stock Bank (NCB)'],
			['NCB', 'NCB'],
			['Nonghyup', 'Nonghyup'],
			['VNNONGHYUPBANK', 'NongHyup Bank'],
			['OJBAVNVX', 'Ocean Commercial Bank (OceanBank)'],
			['Oceanbank', 'Oceanbank'],
			['OCB', 'Orient Commercial Joint Stock Bank'],
			['ORCOVNVX', 'Orient Commercial Joint Stock Bank (OCB)'],
			['PGBank', 'Petrolimex Group Commercial Joint Stock Bank'],
			['VNPGBANK', 'Petrolimex Group Commercial Joint Stock Bank (PGBank)'],
			['PVcomBank', 'PetroVietnam Construction Commercial Joint Stock Bank'],
			['VNPGBANKPETRGROUCOMMJOINSTOCBANK', 'PG Bank-Petrolimex Group Commercial Joint Stock Bank'],
			['PGBLVNVX', 'Prosperity and Growth Commercial Joint Stock Bank (PGBank)'],
			['VIDPVNVX', 'Public Bank Vietnam Limited'],
			['SHB', 'Saigon - Hanoi Commercial Joint Stock Bank'],
			['SBITVNVX', 'Saigon Bank for Industry and Trade (Saigonbank)'],
			['SCBank', 'Saigon Commercial Bank'],
			['SACLVNVX', 'Saigon Commercial Bank (SCB)'],
			['SacomBank', 'Saigon Thuong Tin Commercial Joint Stock Bank'],
			['SGTTVNVX', 'Saigon Thuong Tin Commercial Joint Stock Bank (Sacombank)'],
			['SHBAVNVX', 'Saigon-Hanoi Commercial Joint Stock Bank (SHB)'],
			['SaigonBank', 'SaigonBank'],
			['SeABank', 'SeABank'],
			['VNSHINHANBANK', 'SHINHAN BANK'],
			['SHBVN', 'Shinhan Bank (Vietnam) Limited'],
			['SHBKVNVX', 'Shinhan Bank Vietnam Limited'],
			['SEAVVNVX', 'Southeast Asia Commercial Joint Stock Bank (SeABank)'],
			['SCBLVNVX', 'Standard Chartered Bank (Vietnam) Limited'],
			['StandardChartered', 'StandardChartered'],
			['SMBCVNVX', 'Sumitomo Mitsui Banking Corporation (SMBC) - Ho Chi Minh City Branch'],
			['Techcombank', 'Techcombank'],
			['Techcombankgh', 'Techcombankgh'],
			['TPBANK', 'Tien Phong Commercial Joint Stock Bank'],
			['TPBVVNVX', 'Tien Phong Commercial Joint Stock Bank (TPBank)'],
			['Timo', 'Timo'],
			['VNTIMO', 'Timo by BVBank'],
			['Ubank', 'Ubank'],
			['VNUBANK', 'Ubank by VPBank'],
			['VNUMEE', 'Umee by Kienlongbank'],
			['UnitedOverseas', 'United Overseas Bank (Vietnam) Limited'],
			['UOVBVNVX', 'United Overseas Bank (Vietnam) Limited'],
			['VNVABVIETASIACOMMJOINSTOCBANK', 'VAB/Vietnam-Asia Commercial Joint Stock Bank'],
			['VIETCOM BANK', 'VCB'],
			['VCBNeo', 'VCBNeo'],
			['VIDPublic Bank', 'VID Public Bank Limited'],
			['VietABank', 'Viet A Commercial Joint Stock Bank'],
			['VNACVNVX', 'Viet A Commercial Joint Stock Bank (VietABank)'],
			['VietCapitalBank', 'Viet Capital Commercial Joint Stock Bank'],
			['VNBVBANK', 'Viet Capital Commercial Joint Stock Bank (BVBank)'],
			['Agribank', 'Vietnam Bank for Agriculture and Rural Development'],
			['VBAAVNVX', 'Vietnam Bank for Agriculture and Rural Development (Agribank)'],
			['VBSP', 'Vietnam Bank for Social Policies'],
			['VNVBSP', 'Vietnam Bank for Social Policies (VBSP)'],
			['VNCBBANK', 'Vietnam Construction Bank (CBBank)'],
			['VNVDB', 'Vietnam Development Bank (VDB)'],
			['EBVIVNVX', 'Vietnam Export Import Commercial Joint Stock Bank (Eximbank)'],
			['VIB', 'Vietnam International Commercial Joint Stock Bank'],
			['VNIBVNVX', 'Vietnam International Commercial Joint Stock Bank (VIB)'],
			['ICBVVNVX', 'Vietnam Joint Stock Commercial Bank for Industry and Trade (VietinBank)'],
			['VietinBank', 'Vietnam Joint Stock Commercial Bank of Industry and Trade'],
			['MSB', 'Vietnam Maritime Commercial Joint Stock Bank'],
			['MCOBVNVX', 'Vietnam Maritime Commercial Joint Stock Bank (MSB)'],
			['VPBank', 'Vietnam Prosperity Joint Stock Commercial Bank'],
			['VPBKVNVX', 'Vietnam Prosperity Joint Stock Commercial Bank (VPBank)'],
			['WBVNVNVX', 'Vietnam Public Joint Stock Commercial Bank (PVcomBank)'],
			['VTCBVNVX', 'Vietnam Technological and Commercial Joint Stock Bank (Techcombank)'],
			['VietBank', 'Vietnam Thuong Tin Commercial Joint Stock Bank'],
			['VNTTVNVX', 'Vietnam Thuong Tin Commercial Joint Stock Bank (Vietbank)'],
			['VRBAVNVX', 'Vietnam-Russia Joint Venture Bank (VRB)'],
			['VRB', 'Vietnam–Russia Joint Venture Bank'],
			['VNVIETTELPAY', 'Viettel Money'],
			['ViettelMoney', 'ViettelMoney'],
			['Vikki Bank', 'Vikki Bank'],
			['VNVIKKI', 'Vikki by HDBank'],
			['Vikki_by_HDBank', 'Vikki_by_HDBank'],
			['VNPTPAY', 'VNPT Pay'],
			['VNPTMoney', 'VNPTMoney'],
			['WOORI', 'Woori Bank (Vietnam) Limited'],
			['HVBKVNVX', 'Woori Bank Vietnam Limited']
		]
	},
	ZA: {
		name: 'South Africa',
		currency: 'ZAR',
		payin: [['35010', 'Online Banking']],
		payout: [
			['ABSA', 'Absa'],
			['NEDBANK', 'NedBank'],
			['STANDARD', 'Standard']
		]
	}
};
